config/routes.rb
Rails.application.routes.draw do
    
  resources :markets
  resources :inventories
  resources :items
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"
  
  get '/login', to: 'login#index'
  get '/login/create'
  get '/login/create/:email/:password', to: 'login#create'
  post 'login/create'
  get '/login/destroy'
  get 'register/new'
  post '/register/create'
  post '/users/create', to:'register#create'

  #------
  get '/profile', to: 'profile#index'
  get '/profile/changePassword'
  get '/main', to: 'main#index'
  get '/permission', to: 'main#permission'

  get '/my_inventory', to: 'my_inventory#index'
  get '/my_inventory/create', to: 'my_inventory#create'
  get '/my_inventory/newItem'
  get '/my_inventory/destroy_item'
  get '/my_inventory/destroy_item/:id', to: 'my_inventory#destroy_item'

  get '/my_market', to: 'my_market#index'
  get '/my_market/buy'
  get 'my_market/index'

  get 'items/my_inventory_item'
  post 'items/create_myInventory'
  get 'items/mynew'
  get 'items/create'
  get 'items/newItem'

  get '/purchase_history', to: 'purchase_history#index'
  get '/sale_history', to: 'sale_history#index'
  get '/top_seller', to: 'top_seller#index'
  get '/top_seller/calculate'
  get '/top_seller/:status/:start_date/:end_date', to: 'top_seller#index'
end

app/models/market.rb
class Market < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :is_logined
  before_action :set_market, only: %i[ show edit update destroy ]
  before_action :role
  before_action :authorization, only: %i[ index ]
  #before_action :authorization, except: [:edit, :show]

  def authorization
    if (@myrole == 'admin')
    
    else
      redirect_to '/permission'
    end
  end
  # GET /markets or /markets.json
  def index
    @markets = Market.all
  end

  # GET /markets/1 or /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
    @editing = false
  end

  # GET /markets/1/edit
  def edit
    @editing = true
  end

  # POST /markets or /markets.json
  def create
    @market = Market.new(market_params)
    if ( User.where(id: @market.user_id) == [] )
      p "======"
      p @market.user_id
      redirect_to "/markets/new", notice: "Invalid user_id. Please try agian."
    elsif ( Item.where(id: @market.item_id) == [] )
      redirect_to "/markets/new", notice: "Invalid item_id. Please try agian."
    else
      respond_to do |format|
        if @market.save
          format.html { redirect_to market_url(@market), notice: "Market was successfully created." }
          format.json { render :show, status: :created, location: @market }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @market.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /markets/1 or /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to market_url(@market), notice: "Market was successfully updated." }
        format.json { render :show, status: :ok, location: @market }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1 or /markets/1.json
  def destroy
    @market.destroy

    respond_to do |format|
      format.html { redirect_to markets_url, notice: "Market was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def market_params
      params.require(:market).permit(:user_id, :item_id, :price, :stock, :lock_version)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_with(model: market) do |form| %>
  <%= form.hidden_field :lock_version %>
  <% if market.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
        <% market.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if (@editing == false) %>
    <div>
      <%= form.label :user_id, style: "display: block" %>
      <%= form.number_field :user_id, :required => true %>
    </div>

    <div>
      <%= form.label :item_id, style: "display: block" %>
      <%= form.number_field :item_id, :required => true %>
    </div>
  <% else %>
    <div>
      <%= form.label :user_id, style: "display: block" %>
      <%= form.number_field :user_id, disabled: true %>
    </div>

    <div>
      <%= form.label :item_id, style: "display: block" %>
      <%= form.number_field :item_id, disabled: true  %>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, :required => true %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock, :required => true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/markets/_market.html.erb
<div id="<%= dom_id market %>">
  <p>
    <strong>User:</strong>
    <%= market.user_id %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= market.item_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= market.price %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= market.stock %>
  </p>

</div>

app/views/markets/edit.html.erb
<h1>Editing market</h1>

<%= render "form", market: @market %>

<br>

<div>
  <%= link_to "Edit more detail", "/items/#{@market.item_id}/edit", class:"btn btn-warning" %>
</div>

<br>
<div>
  <%= link_to "Show this market", @market %> |
  <% if (@myrole == 'admin') %>
    <%= link_to "Back to markets", markets_path, class:"btn btn-info" %>
  <% end %>
  <%= link_to "Back to Inventory", '/my_inventory', class:"btn btn-info" %>
</div>

app/views/markets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Markets</h1>

<div id="markets">
  <% @markets.each do |market| %>
    <%= render market %>
    <p>
      <%= link_to "Show this market", market %>
    </p>
  <% end %>
</div>

<%= link_to "New market", new_market_path %>

app/views/markets/new.html.erb
<h1>New market</h1>

<%= render "form", market: @market %>

<br>

<div>
  <% if (@myrole == 'admin') %>
    <%= link_to "Back to markets", markets_path, class:"btn btn-info" %>
  <% end %>
  <%= link_to "Back to Inventory", '/my_inventory', class:"btn btn-info" %>
</div>

app/views/markets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @market %>

<div>
  <%= link_to "Edit this market", edit_market_path(@market) %> |
  <% if (@myrole == 'admin') %>
    <%= link_to "Back to markets", markets_path, class:"btn btn-info" %>
    <%= button_to "Destroy this market", @market, method: :delete %>
  <% end %>
  <%= link_to "Back to Inventory", '/my_inventory', class:"btn btn-info" %>
</div>